name: ci

on: [push]

jobs:
  tests:
    name: Tests with Foundry
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Build huffc
        run: cargo build -r --bin huffc --manifest-path=lib/huff-rs/Cargo.toml --target-dir .

      - name: Run tests
        run: ./release/huffc test/HuffTest.t.huff test -f hufftest
